services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn
        --bind 0.0.0.0:8000
        --workers 3
        text_analyzer.wsgi:application
    env_file:
      - .env
    volumes:
      - static_volume:/app/analyzer/static
    depends_on:
      - db
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/analyzer/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - frontend

volumes:
  postgres_data:
  static_volume:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge